library(lubridate)
library(data.table)
mydatax <- suppressWarnings(fread("exdata_data_household_power_consumption/household_power_consumption.txt", sep = ";", header = TRUE, na.strings = "?"))
mydata2 <- subset(mydatax, mydatax$Date == "1/2/2007" | mydatax$Date == "2/2/2007")
mydata2 <- as.data.frame(mydata2)
id <- c(3:8)
mydata2[,id] <- as.numeric(as.character(unlist(mydata2[,id])))
mydata2$date_time = dmy_hms(paste(mydata2$Date, mydata2$Time))
png(filename = "plot3.png" )
plot(mydata2$date_time, mydata2$Sub_metering_1,  col = "grey", type = "l", xlab = "", ylab = "Energy Sub Metering")
lines(mydata2$date_time, mydata2$Sub_metering_2, type = "l", col = "red")
lines(mydata2$date_time, mydata2$Sub_metering_3, type = "l", col = "blue")
legend("topright", lty = 1, lwd = 1 , col = c("grey", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()